# Project-wide Gradle settings.

# IDE (Android Studio) settings:
# These settings can be overridden in the local.properties file.

# Specifies the JVM arguments for the daemon.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# Use this option only in multi-project builds.
# org.gradle.parallel=true

# AndroidX ve Derleme Desteği Ayarları:
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=33
